app:
  eureka-username: u
  eureka-password: p

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    org:
      springframework:
        security: trace

server:
  port: 9999
    
spring:
  application:
    name: authorization-server
  threads:
    virtual:
      enabled: true