app:
  eureka-username: u
  eureka-password: p

server:
  port: 8443
  ssl:
    key-alias: localhost
    key-store: classpath:keystore/edge.p12
    key-store-type: PKCS12
    key-store-password: password
    

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: restful-api-demo
        uri: lb://restful-api-demo
        predicates:
        - Path=/api/demo/**
        filters: 
        - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999
        
management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
          